<?php

namespace Database\Seeders;

use App\Models\Pokemon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PokemonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pokemons = [
            ['name' => 'Bulbasaur', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif', 'ability' => 'Overgrow'],
            ['name' => 'Ivysaur', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif', 'ability' => 'Overgrow'],
            ['name' => 'Venusaur', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif', 'ability' => 'Overgrow'],
            ['name' => 'Charmander', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif', 'ability' => 'Blaze'],
            ['name' => 'Charmeleon', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif', 'ability' => 'Blaze'],
            ['name' => 'Charizard', 'type' => 'Fire/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif', 'ability' => 'Blaze'],
            ['name' => 'Squirtle', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif', 'ability' => 'Torrent'],
            ['name' => 'Wartortle', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif', 'ability' => 'Torrent'],
            ['name' => 'Blastoise', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif', 'ability' => 'Torrent'],
            ['name' => 'Caterpie', 'type' => 'Bug', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif', 'ability' => 'Shield Dust'],
            ['name' => 'Metapod', 'type' => 'Bug', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif', 'ability' => 'Shed Skin'],
            ['name' => 'Butterfree', 'type' => 'Bug/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif', 'ability' => 'Compound Eyes'],
            ['name' => 'Weedle', 'type' => 'Bug/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif', 'ability' => 'Shield Dust'],
            ['name' => 'Kakuna', 'type' => 'Bug/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif', 'ability' => 'Shed Skin'],
            ['name' => 'Beedrill', 'type' => 'Bug/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif', 'ability' => 'Swarm'],
            ['name' => 'Pidgey', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Pidgeotto', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Pidgeot', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Rattata', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif', 'ability' => 'Run Away'],
            ['name' => 'Raticate', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif', 'ability' => 'Run Away'],
            ['name' => 'Spearow', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Fearow', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Ekans', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif', 'ability' => 'Intimidate'],
            ['name' => 'Arbok', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif', 'ability' => 'Intimidate'],
            ['name' => 'Pikachu', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif', 'ability' => 'Static'],
            ['name' => 'Raichu', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif', 'ability' => 'Static'],
            ['name' => 'Sandshrew', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/sandshrew.gif', 'ability' => 'Sand Veil'],
            ['name' => 'Sandslash', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif', 'ability' => 'Sand Veil'],
            ['name' => 'Nidoran♀', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-f.gif', 'ability' => 'Poison Point'],
            ['name' => 'Nidorina', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif', 'ability' => 'Poison Point'],
            ['name' => 'Nidoqueen', 'type' => 'Poison/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif', 'ability' => 'Poison Point'],
            ['name' => 'Nidoran♂', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-m.gif', 'ability' => 'Poison Point'],
            ['name' => 'Nidorino', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif', 'ability' => 'Poison Point'],
            ['name' => 'Nidoking', 'type' => 'Poison/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif', 'ability' => 'Poison Point'],
            ['name' => 'Clefairy', 'type' => 'Fairy', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif', 'ability' => 'Cute Charm'],
            ['name' => 'Clefable', 'type' => 'Fairy', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif', 'ability' => 'Cute Charm'],
            ['name' => 'Vulpix', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif', 'ability' => 'Flash Fire'],
            ['name' => 'Ninetales', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif', 'ability' => 'Flash Fire'],
            ['name' => 'Jigglypuff', 'type' => 'Normal/Fairy', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif', 'ability' => 'Cute Charm'],
            ['name' => 'Wigglytuff', 'type' => 'Normal/Fairy', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif', 'ability' => 'Cute Charm'],
            ['name' => 'Zubat', 'type' => 'Poison/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif', 'ability' => 'Inner Focus'],
            ['name' => 'Golbat', 'type' => 'Poison/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif', 'ability' => 'Inner Focus'],
            ['name' => 'Oddish', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Gloom', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Vileplume', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Paras', 'type' => 'Bug/Grass', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif', 'ability' => 'Effect Spore'],
            ['name' => 'Parasect', 'type' => 'Bug/Grass', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif', 'ability' => 'Effect Spore'],
            ['name' => 'Venonat', 'type' => 'Bug/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif', 'ability' => 'Compound Eyes'],
            ['name' => 'Venomoth', 'type' => 'Bug/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif', 'ability' => 'Shield Dust'],
            ['name' => 'Diglett', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif', 'ability' => 'Sand Veil'],
            ['name' => 'Dugtrio', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif', 'ability' => 'Sand Veil'],
            ['name' => 'Meowth', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif', 'ability' => 'Pickup'],
            ['name' => 'Persian', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif', 'ability' => 'Limber'],
            ['name' => 'Psyduck', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif', 'ability' => 'Damp'],
            ['name' => 'Golduck', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif', 'ability' => 'Damp'],
            ['name' => 'Mankey', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif', 'ability' => 'Vital Spirit'],
            ['name' => 'Primeape', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif', 'ability' => 'Vital Spirit'],
            ['name' => 'Growlithe', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif', 'ability' => 'Intimidate'],
            ['name' => 'Arcanine', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif', 'ability' => 'Intimidate'],
            ['name' => 'Poliwag', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif', 'ability' => 'Water Absorb'],
            ['name' => 'Poliwhirl', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif', 'ability' => 'Water Absorb'],
            ['name' => 'Poliwrath', 'type' => 'Water/Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif', 'ability' => 'Water Absorb'],
            ['name' => 'Abra', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif', 'ability' => 'Synchronize'],
            ['name' => 'Kadabra', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif', 'ability' => 'Synchronize'],
            ['name' => 'Alakazam', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif', 'ability' => 'Synchronize'],
            ['name' => 'Machop', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif', 'ability' => 'Guts'],
            ['name' => 'Machoke', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif', 'ability' => 'Guts'],
            ['name' => 'Machamp', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif', 'ability' => 'Guts'],
            ['name' => 'Bellsprout', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Weepinbell', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Victreebel', 'type' => 'Grass/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Tentacool', 'type' => 'Water/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacool.gif', 'ability' => 'Clear Body'],
            ['name' => 'Tentacruel', 'type' => 'Water/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif', 'ability' => 'Clear Body'],
            ['name' => 'Geodude', 'type' => 'Rock/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif', 'ability' => 'Rock Head'],
            ['name' => 'Graveler', 'type' => 'Rock/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif', 'ability' => 'Rock Head'],
            ['name' => 'Golem', 'type' => 'Rock/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif', 'ability' => 'Rock Head'],
            ['name' => 'Ponyta', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif', 'ability' => 'Run Away'],
            ['name' => 'Rapidash', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif', 'ability' => 'Run Away'],
            ['name' => 'Slowpoke', 'type' => 'Water/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif', 'ability' => 'Oblivious'],
            ['name' => 'Slowbro', 'type' => 'Water/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif', 'ability' => 'Oblivious'],
            ['name' => 'Magnemite', 'type' => 'Electric/Steel', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif', 'ability' => 'Magnet Pull'],
            ['name' => 'Magneton', 'type' => 'Electric/Steel', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif', 'ability' => 'Magnet Pull'],
            ['name' => 'Farfetch\'d', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/farfetchd.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Doduo', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif', 'ability' => 'Run Away'],
            ['name' => 'Dodrio', 'type' => 'Normal/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif', 'ability' => 'Run Away'],
            ['name' => 'Seel', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif', 'ability' => 'Thick Fat'],
            ['name' => 'Dewgong', 'type' => 'Water/Ice', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif', 'ability' => 'Thick Fat'],
            ['name' => 'Grimer', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif', 'ability' => 'Stench'],
            ['name' => 'Muk', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif', 'ability' => 'Stench'],
            ['name' => 'Shellder', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif', 'ability' => 'Shell Armor'],
            ['name' => 'Cloyster', 'type' => 'Water/Ice', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif', 'ability' => 'Shell Armor'],
            ['name' => 'Gastly', 'type' => 'Ghost/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif', 'ability' => 'Levitate'],
            ['name' => 'Haunter', 'type' => 'Ghost/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif', 'ability' => 'Levitate'],
            ['name' => 'Gengar', 'type' => 'Ghost/Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif', 'ability' => 'Levitate'],
            ['name' => 'Onix', 'type' => 'Rock/Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif', 'ability' => 'Rock Head'],
            ['name' => 'Drowzee', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif', 'ability' => 'Insomnia'],
            ['name' => 'Hypno', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif', 'ability' => 'Insomnia'],
            ['name' => 'Krabby', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif', 'ability' => 'Hyper Cutter'],
            ['name' => 'Kingler', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif', 'ability' => 'Hyper Cutter'],
            ['name' => 'Voltorb', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif', 'ability' => 'Soundproof'],
            ['name' => 'Electrode', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif', 'ability' => 'Soundproof'],
            ['name' => 'Exeggcute', 'type' => 'Grass/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Exeggutor', 'type' => 'Grass/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Cubone', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif', 'ability' => 'Rock Head'],
            ['name' => 'Marowak', 'type' => 'Ground', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif', 'ability' => 'Rock Head'],
            ['name' => 'Hitmonlee', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif', 'ability' => 'Limber'],
            ['name' => 'Hitmonchan', 'type' => 'Fighting', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif', 'ability' => 'Keen Eye'],
            ['name' => 'Lickitung', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif', 'ability' => 'Own Tempo'],
            ['name' => 'Koffing', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif', 'ability' => 'Levitate'],
            ['name' => 'Weezing', 'type' => 'Poison', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif', 'ability' => 'Levitate'],
            ['name' => 'Rhyhorn', 'type' => 'Ground/Rock', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif', 'ability' => 'Lightning Rod'],
            ['name' => 'Rhydon', 'type' => 'Ground/Rock', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif', 'ability' => 'Lightning Rod'],
            ['name' => 'Chansey', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif', 'ability' => 'Natural Cure'],
            ['name' => 'Tangela', 'type' => 'Grass', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif', 'ability' => 'Chlorophyll'],
            ['name' => 'Kangaskhan', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif', 'ability' => 'Early Bird'],
            ['name' => 'Horsea', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Seadra', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif', 'ability' => 'Poison Point'],
            ['name' => 'Goldeen', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Seaking', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Staryu', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif', 'ability' => 'Natural Cure'],
            ['name' => 'Starmie', 'type' => 'Water/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif', 'ability' => 'Natural Cure'],
            ['name' => 'Mr. Mime', 'type' => 'Psychic/Fairy', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/mr-mime.gif', 'ability' => 'Soundproof'],
            ['name' => 'Scyther', 'type' => 'Bug/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif', 'ability' => 'Swarm'],
            ['name' => 'Jynx', 'type' => 'Ice/Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif', 'ability' => 'Oblivious'],
            ['name' => 'Electabuzz', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif', 'ability' => 'Static'],
            ['name' => 'Magmar', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif', 'ability' => 'Flame Body'],
            ['name' => 'Pinsir', 'type' => 'Bug', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif', 'ability' => 'Hyper Cutter'],
            ['name' => 'Tauros', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif', 'ability' => 'Intimidate'],
            ['name' => 'Magikarp', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Gyarados', 'type' => 'Water/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif', 'ability' => 'Intimidate'],
            ['name' => 'Lapras', 'type' => 'Water/Ice', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif', 'ability' => 'Water Absorb'],
            ['name' => 'Ditto', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif', 'ability' => 'Limber'],
            ['name' => 'Eevee', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif', 'ability' => 'Run Away'],
            ['name' => 'Vaporeon', 'type' => 'Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif', 'ability' => 'Water Absorb'],
            ['name' => 'Jolteon', 'type' => 'Electric', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif', 'ability' => 'Volt Absorb'],
            ['name' => 'Flareon', 'type' => 'Fire', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif', 'ability' => 'Flash Fire'],
            ['name' => 'Porygon', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif', 'ability' => 'Trace'],
            ['name' => 'Omanyte', 'type' => 'Rock/Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Omastar', 'type' => 'Rock/Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Kabuto', 'type' => 'Rock/Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Kabutops', 'type' => 'Rock/Water', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif', 'ability' => 'Swift Swim'],
            ['name' => 'Aerodactyl', 'type' => 'Rock/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif', 'ability' => 'Rock Head'],
            ['name' => 'Snorlax', 'type' => 'Normal', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif', 'ability' => 'Immunity'],
            ['name' => 'Articuno', 'type' => 'Ice/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif', 'ability' => 'Pressure'],
            ['name' => 'Zapdos', 'type' => 'Electric/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif', 'ability' => 'Pressure'],
            ['name' => 'Moltres', 'type' => 'Fire/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif', 'ability' => 'Pressure'],
            ['name' => 'Dratini', 'type' => 'Dragon', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif', 'ability' => 'Shed Skin'],
            ['name' => 'Dragonair', 'type' => 'Dragon', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif', 'ability' => 'Shed Skin'],
            ['name' => 'Dragonite', 'type' => 'Dragon/Flying', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif', 'ability' => 'Inner Focus'],
            ['name' => 'Mewtwo', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif', 'ability' => 'Pressure'],
            ['name' => 'Mew', 'type' => 'Psychic', 'img_url' => 'https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif', 'ability' => 'Synchronize'],
        ];
        foreach ($pokemons as $index => $singlePokemonData) {

            $pokemon = new Pokemon();
            $pokemon->name = $singlePokemonData['name'];
            $pokemon->pokedex_index = $index+1;
            $pokemon->type = $singlePokemonData['type'];
            $pokemon->img_url = $singlePokemonData['img_url'];
            $pokemon->ability = $singlePokemonData['ability'];
            $pokemon->save();
        }
    }
}
